### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by saadsaifse** [thuanmb/react-mapbox-gl-cluster#12]
Setup: Create-React-App with Typescript. Getting the following error. suggestions?
```
OverridedCluster.Cluster.UNSAFE_componentWillMount
src/cluster.tsx:75
  72 | _this.zoomToClusterBounds = function (event) {
  73 |     var markers = Array.prototype.slice.call(event.currentTarget.children);
  74 |     var marker = _this.findMarkerElement(event.currentTarget, event.target);
> 75 |     var index = markers.indexOf(marker);
     | ^  76 |     var cluster = _this.state.clusterPoints[index];
  77 |     if (!cluster.properties || !cluster.properties.cluster_id) {
  78 |         return;
```

**Comment by thuanmb** [comment]
Which is the error message?

**Comment by saadsaifse** [comment]
`TypeError: Cannot read property 'on' of undefined`

**Comment by thuanmb** [comment]
Can you share a reproducible repository? Seem you above code and message is not related to each other.

**Comment by macduff111** [comment]
Hi, I have the same error message, in the code below, map appears to undefined  

`
	Cluster.prototype.UNSAFE_componentWillMount = function () {
	var _a = this.props,
		children = _a.children,
		map = _a.map;

	if (children) {
		this.childrenChange(children);
	}

	map.on('move', this.mapChange);
	map.on('zoom', this.mapChange);
	this.mapChange();
	};
`

**Comment by thuanmb** [comment]
I tried to reproduce the issue with my current example. But I cannot. Can you share a minimal reproducible repository, so that I can debug the issue @macduff111?

**Comment by macduff111** [comment]
sure - https://bitbucket.org/macduff111/react-mapbox-gl-cluster-test/src/master/
this is an empty project made with create-react-app to which I've added your basic example. I get same error message
`TypeError: Cannot read property 'on' of undefined`

**Comment by MPZMail** [comment]
We have the same issue also. We've just updated react to latest version along with mapbox.

**Comment by thuanmb** [comment]
Can you disable the strict mode when bundling. There are some error with using "UNSAFE_*" from ReactJS from react-mapbox-gl library?

**Comment by MPZMail** [comment]
I actually pulled the latest version and rebuilt without doing this and it rebuilt correctly. Whatever you did in your last push fixed it for us 👍

**Comment by thuanmb** [comment]
@macduff111 the issue was fixed on latest version. There are some CSS issue which prevent you to see the map. Can you help to fix it by:
```
# App.css
.App {
	height: 100vh;
	text-align: center;
}

.mapboxgl-map {
	height: 100%;
}

.mapboxgl-popup {
	z-index: 999;
}
```
and:
```
// App.js
...
import "./App.css";
...
```

**Comment by Crisis2010** [comment]
The problem still exists.

Check: https://stackblitz.com/edit/react-dgbywh

**Comment by thuanmb** [comment]
@Crisis2010 fixed at 1.9.0

**Comment by jesperkc** [comment]
@thuanmb doesn't seem to be fixed

https://stackblitz.com/edit/react-dy3kzz

**Comment by thuanmb** [comment]
@jesperkc the `"mapbox-gl": "1.19.0"` doesn't exist. I tried to use v1.11.0 and it works. Can you help to check again?
Refs: https://www.npmjs.com/package/mapbox-gl

**Comment by jesperkc** [comment]
@thuanmb awesome it works for me :)
